
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class JList extends javax.swing.JFrame {


    /**
     * Creates new form JList
     */
    public JList() {
        initComponents();
        modelList.addElement(4);
        modelList.addElement(5);
        modelList.addElement(6);
        modelList.addElement(9);
        modelList.addElement(11);
        modelList.addElement(17);
        modelList.addElement(18);
        lstItem.setModel(modelList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTodensochan = new javax.swing.JButton();
        btnTodensonguyento = new javax.swing.JButton();
        btnTodensole = new javax.swing.JButton();
        btnBotoden = new javax.swing.JButton();
        btnXoacacgiatritoden = new javax.swing.JButton();
        btnTonggiatrilist = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNhap = new javax.swing.JButton();
        txtNhap = new javax.swing.JTextField();
        chkNhapSoAm = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstItem = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Chon tac vu"));

        btnTodensochan.setText("To den so chan");
        btnTodensochan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodensochanActionPerformed(evt);
            }
        });

        btnTodensonguyento.setText("To den so nguyen to");
        btnTodensonguyento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodensonguyentoActionPerformed(evt);
            }
        });

        btnTodensole.setText("To den so le");
        btnTodensole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodensoleActionPerformed(evt);
            }
        });

        btnBotoden.setText("Bo to den");
        btnBotoden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotodenActionPerformed(evt);
            }
        });

        btnXoacacgiatritoden.setText("Xoa cac gia tri dang to den");
        btnXoacacgiatritoden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoacacgiatritodenActionPerformed(evt);
            }
        });

        btnTonggiatrilist.setText("Tong gia tri trong list");
        btnTonggiatrilist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTonggiatrilistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoacacgiatritoden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBotoden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTodensonguyento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTodensole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTodensochan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTonggiatrilist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnTodensochan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTodensole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTodensonguyento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBotoden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoacacgiatritoden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTonggiatrilist)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nhap thong tin"));

        btnNhap.setText("Nhap");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        chkNhapSoAm.setText("Nhap so am");

        jScrollPane2.setViewportView(lstItem);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkNhapSoAm)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhap)
                    .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkNhapSoAm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel modelList = new DefaultListModel();
    int[] selectedItemList = null;
    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here:
                int inputNumber = 0; 
 
        try { 
            inputNumber = Integer.parseInt(txtNhap.getText().toString()); 
 
            if (inputNumber < 0 && !chkNhapSoAm.isSelected()) { 
                JOptionPane.showMessageDialog(this, "Khong duoc nhap so am", "Canh Bao",JOptionPane.ERROR_MESSAGE); 
            }  else { 
                modelList.addElement(inputNumber); 
                txtNhap.setText(""); 
            } 
 
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(this, "Vui long nhap so", "Canh Bao",JOptionPane.ERROR_MESSAGE); 
            txtNhap.setText(""); 
        } 
    }//GEN-LAST:event_btnNhapActionPerformed

    private void btnTodensochanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodensochanActionPerformed
        // TODO add your handling code here:
        getListItems("EVEN"); 
        lstItem.setSelectedIndices(selectedItemList); 
    }//GEN-LAST:event_btnTodensochanActionPerformed

    private void btnTodensoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodensoleActionPerformed
        // TODO add your handling code here:
        getListItems("ODD"); 
        lstItem.setSelectedIndices(selectedItemList); 
    }//GEN-LAST:event_btnTodensoleActionPerformed

    private void btnTodensonguyentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodensonguyentoActionPerformed
        // TODO add your handling code here:
        getListItems("PRIME");
        lstItem.setSelectedIndices(selectedItemList);
    }//GEN-LAST:event_btnTodensonguyentoActionPerformed

    private void btnBotodenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotodenActionPerformed
        // TODO add your handling code here:
        if (lstItem.getSelectedIndex() == -1) { 
            JOptionPane.showMessageDialog(this, "Ban chua chon so nao", "Canh Bao", JOptionPane.ERROR_MESSAGE); 
        } else { 
            lstItem.removeSelectionInterval(selectedItemList[0], selectedItemList[selectedItemList.length - 1]); 
        } 
    }//GEN-LAST:event_btnBotodenActionPerformed

    private void btnXoacacgiatritodenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoacacgiatritodenActionPerformed
        // TODO add your handling code here:
                if (lstItem.getSelectedIndex() == -1) { 
            JOptionPane.showMessageDialog(this, "Ban chua chon so nao", "Canh Bao", JOptionPane.ERROR_MESSAGE); 
        } else { 
            for (int i = 0; i < selectedItemList.length; i++) { 
                modelList.removeElement(lstItem.getSelectedValue()); 
            } 
        } 
    }//GEN-LAST:event_btnXoacacgiatritodenActionPerformed

    private void btnTonggiatrilistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTonggiatrilistActionPerformed
        // TODO add your handling code here:
                if (modelList.size() == 0) { 
            JOptionPane.showMessageDialog(this, "Danh sach bi rong", "Canh Bao", JOptionPane.WARNING_MESSAGE); 
        } else { 
            int sum = 0; 
            for (int i = 0; i < modelList.size(); i++) 
{ 
                int num = Integer.parseInt(modelList.get(i).toString()); 
                sum += num; 
            } 
 
            JOptionPane.showMessageDialog(this, "Tong cac con so trong JList: " + sum); 
        } 
    }//GEN-LAST:event_btnTonggiatrilistActionPerformed

    private void getListItems(String type) { 
        // dung array list chua cac gia tri trong danh sach JList 
        ArrayList<Integer> arrList = new ArrayList<Integer>(); 
 
        if (type.equals("EVEN")) { 
            for (int i = 0; i < modelList.size(); i++) 
            { 
                int item = Integer.parseInt(modelList.get(i).toString()); 
                if (item % 2 == 0) { 
                    arrList.add(i); 
                } 
            } 
            selectedItemList = new int[arrList.size()]; 
 
            for (int i = 0; i < arrList.size(); i++) { 
                selectedItemList[i] = arrList.get(i); 
            } 
        } else if (type.equals("PRIME")) { 
            for (int i = 0; i < modelList.size(); i++) 
            { 
                int item = Integer.parseInt(modelList.get(i).toString()); 
                if (isPrime(item)) { 
                    arrList.add(i); 
                } 
            } 
            selectedItemList = new int[arrList.size()]; 
             
            for (int i = 0; i < arrList.size(); i++) { 
                selectedItemList[i] = arrList.get(i); 
            } 
        } else if (type.equals("ODD")) { 
            for (int i = 0; i < modelList.size(); i++) 
            { 
                int item = Integer.parseInt(modelList.get(i).toString()); 
                if (item % 2 == 1) { 
                    arrList.add(i); 
                } 
            } 
            selectedItemList = new int[arrList.size()]; 
 
            for (int i = 0; i < arrList.size(); i++) { 
                selectedItemList[i] = arrList.get(i); 
            } 
        } 
    } 
    private boolean isPrime(int number) { 
            if (number <= 1) { 
                return false; 
            } 

            for (int i = 2; i < number; i++) { 
                if (number % i == 0) { 
                    return false; 
                } 
            } 
            return true; 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JList().setVisible(true);
            }
        });
    }
	//ashdkashdkjahsdkjasdhkjashdkjahsdkjhasdkjhasd

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotoden;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnTodensochan;
    private javax.swing.JButton btnTodensole;
    private javax.swing.JButton btnTodensonguyento;
    private javax.swing.JButton btnTonggiatrilist;
    private javax.swing.JButton btnXoacacgiatritoden;
    private javax.swing.JCheckBox chkNhapSoAm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstItem;
    private javax.swing.JTextField txtNhap;
    // End of variables declaration//GEN-END:variables
}
